export const COMMUTE_BUFFER_MINUTES = 3;
export const MAX_ORIGIN_WALK_MINUTES = 12;
export const MAX_DESTINATION_WALK_MINUTES = 15;
export const MAX_ROUTE_WALK_MINUTES = 15;
export const MAX_RECOMMENDED_STATIONS = 16;
export const MAX_RECOMMENDED_PROPERTIES = 48;
