import type { PropertyMatch } from "./commute-types";

const lifestyle = {
  nearestSupermarketWalkMinutes: 5,
  supermarketsWithin10Minutes: 4,
  convenienceStoresWithin10Minutes: 7,
  restaurantsWithin10Minutes: 18,
  dataSource: "generated_mock" as const,
};

export const HOUSING_CALIBRATION_PROPERTIES: PropertyMatch[] = [
  {
    id: "dna-compact-near-station",
    slug: "dna-compact-near-station",
    title: "近站コンパクト 1K",
    address: "偏好测试用 Demo 房源 A",
    monthlyRentYen: 92000,
    managementFeeYen: 6000,
    layout: "1K",
    areaSqm: 21.5,
    buildingAgeYears: 7,
    floor: 5,
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267d",
    sourceUrl: null,
    lifestyle: { ...lifestyle, nearestSupermarketWalkMinutes: 4 },
    station: { key: "dna-station-a", name: "近站エリア", nameJa: "近駅エリア", walkingMinutes: 3 },
    commute: { propertyWalkMinutes: 3, stationToDestinationMinutes: 25, finalMinutes: 28, route: "测试路线 A" },
  },
  {
    id: "dna-large-value-room",
    slug: "dna-large-value-room",
    title: "宽敞高性价比 1R",
    address: "偏好测试用 Demo 房源 B",
    monthlyRentYen: 76000,
    managementFeeYen: 4000,
    layout: "1R",
    areaSqm: 29.2,
    buildingAgeYears: 19,
    floor: 2,
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    sourceUrl: null,
    lifestyle: { ...lifestyle, restaurantsWithin10Minutes: 9 },
    station: { key: "dna-station-b", name: "住宅街エリア", nameJa: "住宅街エリア", walkingMinutes: 11 },
    commute: { propertyWalkMinutes: 11, stationToDestinationMinutes: 24, finalMinutes: 35, route: "测试路线 B" },
  },
  {
    id: "dna-new-lifestyle-home",
    slug: "dna-new-lifestyle-home",
    title: "新築生活便利 1DK",
    address: "偏好测试用 Demo 房源 C",
    monthlyRentYen: 112000,
    managementFeeYen: 8000,
    layout: "1DK",
    areaSqm: 27.8,
    buildingAgeYears: 2,
    floor: 7,
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    sourceUrl: null,
    lifestyle: {
      nearestSupermarketWalkMinutes: 2,
      supermarketsWithin10Minutes: 7,
      convenienceStoresWithin10Minutes: 12,
      restaurantsWithin10Minutes: 34,
      dataSource: "generated_mock",
    },
    station: { key: "dna-station-c", name: "繁华街エリア", nameJa: "繁華街エリア", walkingMinutes: 6 },
    commute: { propertyWalkMinutes: 6, stationToDestinationMinutes: 32, finalMinutes: 38, route: "测试路线 C" },
  },
  {
    id: "dna-budget-long-commute",
    slug: "dna-budget-long-commute",
    title: "低租金通勤取舍 1K",
    address: "偏好测试用 Demo 房源 D",
    monthlyRentYen: 72000,
    managementFeeYen: 5000,
    layout: "1K",
    areaSqm: 24.4,
    buildingAgeYears: 12,
    floor: 3,
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    sourceUrl: null,
    lifestyle: { ...lifestyle, nearestSupermarketWalkMinutes: 7, restaurantsWithin10Minutes: 6 },
    station: { key: "dna-station-d", name: "郊外エリア", nameJa: "郊外エリア", walkingMinutes: 7 },
    commute: { propertyWalkMinutes: 7, stationToDestinationMinutes: 42, finalMinutes: 49, route: "测试路线 D" },
  },
  {
    id: "dna-one-minute-old-studio",
    slug: "dna-one-minute-old-studio",
    title: "駅徒歩1分レトロ 1R",
    address: "偏好测试用 Demo 房源 E",
    monthlyRentYen: 99000,
    managementFeeYen: 6000,
    layout: "1R",
    areaSqm: 18.3,
    buildingAgeYears: 24,
    floor: 4,
    imageUrl: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9",
    sourceUrl: null,
    lifestyle: { ...lifestyle, nearestSupermarketWalkMinutes: 3 },
    station: { key: "dna-station-e", name: "駅前エリア", nameJa: "駅前エリア", walkingMinutes: 1 },
    commute: { propertyWalkMinutes: 1, stationToDestinationMinutes: 24, finalMinutes: 25, route: "测试路线 E" },
  },
  {
    id: "dna-large-new-far-station",
    slug: "dna-large-new-far-station",
    title: "広々新築 1DK",
    address: "偏好测试用 Demo 房源 F",
    monthlyRentYen: 121000,
    managementFeeYen: 9000,
    layout: "1DK",
    areaSqm: 35.6,
    buildingAgeYears: 1,
    floor: 8,
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    sourceUrl: null,
    lifestyle: { ...lifestyle, nearestSupermarketWalkMinutes: 8, convenienceStoresWithin10Minutes: 3 },
    station: { key: "dna-station-f", name: "新住宅地エリア", nameJa: "新住宅地エリア", walkingMinutes: 14 },
    commute: { propertyWalkMinutes: 14, stationToDestinationMinutes: 22, finalMinutes: 36, route: "测试路线 F" },
  },
  {
    id: "dna-city-life-compact",
    slug: "dna-city-life-compact",
    title: "都心生活充実 1R",
    address: "偏好测试用 Demo 房源 G",
    monthlyRentYen: 108000,
    managementFeeYen: 7000,
    layout: "1R",
    areaSqm: 22.8,
    buildingAgeYears: 18,
    floor: 6,
    imageUrl: "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d",
    sourceUrl: null,
    lifestyle: {
      nearestSupermarketWalkMinutes: 2,
      supermarketsWithin10Minutes: 8,
      convenienceStoresWithin10Minutes: 15,
      restaurantsWithin10Minutes: 48,
      dataSource: "generated_mock",
    },
    station: { key: "dna-station-g", name: "都心生活エリア", nameJa: "都心生活エリア", walkingMinutes: 5 },
    commute: { propertyWalkMinutes: 5, stationToDestinationMinutes: 29, finalMinutes: 34, route: "测试路线 G" },
  },
  {
    id: "dna-direct-route-value",
    slug: "dna-direct-route-value",
    title: "乗換なし実用派 1K",
    address: "偏好测试用 Demo 房源 H",
    monthlyRentYen: 79000,
    managementFeeYen: 5000,
    layout: "1K",
    areaSqm: 25.1,
    buildingAgeYears: 14,
    floor: 2,
    imageUrl: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
    sourceUrl: null,
    lifestyle: { ...lifestyle, supermarketsWithin10Minutes: 2, restaurantsWithin10Minutes: 7 },
    station: { key: "dna-station-h", name: "直通沿線エリア", nameJa: "直通沿線エリア", walkingMinutes: 8 },
    commute: { propertyWalkMinutes: 8, stationToDestinationMinutes: 33, finalMinutes: 41, route: "换乘 0 次测试路线 H" },
  },
  {
    id: "dna-balanced-suburban",
    slug: "dna-balanced-suburban",
    title: "バランス型 1K",
    address: "偏好测试用 Demo 房源 I",
    monthlyRentYen: 87000,
    managementFeeYen: 6000,
    layout: "1K",
    areaSqm: 27,
    buildingAgeYears: 8,
    floor: 5,
    imageUrl: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    sourceUrl: null,
    lifestyle: { ...lifestyle, nearestSupermarketWalkMinutes: 6, restaurantsWithin10Minutes: 8 },
    station: { key: "dna-station-i", name: "住宅地エリア", nameJa: "住宅地エリア", walkingMinutes: 6 },
    commute: { propertyWalkMinutes: 6, stationToDestinationMinutes: 26, finalMinutes: 32, route: "测试路线 I" },
  },
  {
    id: "dna-premium-all-rounder",
    slug: "dna-premium-all-rounder",
    title: "都心プレミアム 1DK",
    address: "偏好测试用 Demo 房源 J",
    monthlyRentYen: 138000,
    managementFeeYen: 10000,
    layout: "1DK",
    areaSqm: 32.5,
    buildingAgeYears: 3,
    floor: 10,
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
    sourceUrl: null,
    lifestyle: {
      nearestSupermarketWalkMinutes: 3,
      supermarketsWithin10Minutes: 6,
      convenienceStoresWithin10Minutes: 11,
      restaurantsWithin10Minutes: 30,
      dataSource: "generated_mock",
    },
    station: { key: "dna-station-j", name: "都心駅近エリア", nameJa: "都心駅近エリア", walkingMinutes: 4 },
    commute: { propertyWalkMinutes: 4, stationToDestinationMinutes: 25, finalMinutes: 29, route: "测试路线 J" },
  },
];
