import type { PropertyMatch } from "./commute-types";

const lifestyle = {
  nearestSupermarketWalkMinutes: 5,
  supermarketsWithin10Minutes: 4,
  convenienceStoresWithin10Minutes: 7,
  restaurantsWithin10Minutes: 18,
  dataSource: "generated_mock" as const,
};

export const HOUSING_CALIBRATION_PROPERTIES: PropertyMatch[] = [
  {
    id: "dna-compact-near-station",
    slug: "dna-compact-near-station",
    title: "近站コンパクト 1K",
    address: "偏好测试用 Demo 房源 A",
    monthlyRentYen: 92000,
    managementFeeYen: 6000,
    layout: "1K",
    areaSqm: 21.5,
    buildingAgeYears: 7,
    floor: 5,
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267d",
    sourceUrl: null,
    lifestyle: { ...lifestyle, nearestSupermarketWalkMinutes: 4 },
    station: { key: "dna-station-a", name: "近站エリア", nameJa: "近駅エリア", walkingMinutes: 3 },
    commute: { propertyWalkMinutes: 3, stationToDestinationMinutes: 25, finalMinutes: 28, route: "测试路线 A" },
  },
  {
    id: "dna-large-value-room",
    slug: "dna-large-value-room",
    title: "宽敞高性价比 1R",
    address: "偏好测试用 Demo 房源 B",
    monthlyRentYen: 76000,
    managementFeeYen: 4000,
    layout: "1R",
    areaSqm: 29.2,
    buildingAgeYears: 19,
    floor: 2,
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    sourceUrl: null,
    lifestyle: { ...lifestyle, restaurantsWithin10Minutes: 9 },
    station: { key: "dna-station-b", name: "住宅街エリア", nameJa: "住宅街エリア", walkingMinutes: 11 },
    commute: { propertyWalkMinutes: 11, stationToDestinationMinutes: 24, finalMinutes: 35, route: "测试路线 B" },
  },
  {
    id: "dna-new-lifestyle-home",
    slug: "dna-new-lifestyle-home",
    title: "新築生活便利 1DK",
    address: "偏好测试用 Demo 房源 C",
    monthlyRentYen: 112000,
    managementFeeYen: 8000,
    layout: "1DK",
    areaSqm: 27.8,
    buildingAgeYears: 2,
    floor: 7,
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    sourceUrl: null,
    lifestyle: {
      nearestSupermarketWalkMinutes: 2,
      supermarketsWithin10Minutes: 7,
      convenienceStoresWithin10Minutes: 12,
      restaurantsWithin10Minutes: 34,
      dataSource: "generated_mock",
    },
    station: { key: "dna-station-c", name: "繁华街エリア", nameJa: "繁華街エリア", walkingMinutes: 6 },
    commute: { propertyWalkMinutes: 6, stationToDestinationMinutes: 32, finalMinutes: 38, route: "测试路线 C" },
  },
];
